spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rose890117$
    url: jdbc:mysql://localhost:3306/springSecurityDemo?serverTimezone=UTC

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

